spring:
  application:
    name: hangouts-planner-bff-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      fail-fast: true
      username: config-client
      password: JnJc&4Y+9:+vFpmg