server:
  port: 8888
  shutdown: graceful

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config

management:
  endpoints:
    web:
      exposure:
        include: "health"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

config-service:
  security:
    spring-security-username: config-client
    spring-security-password: "{noop}JnJc&4Y+9:+vFpmg"
    encrypt-key: ";*LYr*8U/3skc:u~"

encrypt:
  key: ${config-service.encrypt-key}
