server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: hangouts-service-api-v1
          uri: lb://hangout-service
          predicates:
            - Path=/api/hangout-service/**
          filters:
            - RewritePath=/api/hangout-service/(?<segment>.*),/api/v1/$\{segment}

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: "health,gateway"
