server:
  port: 8083

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9990/auth/realms/hangouts-planner"
          jwk-set-uri: "http://localhost:9990/auth/realms/hangouts-planner/protocol/openid-connect/certs"
          jws-algorithms: RS256

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

feign:
  client:
    config:
      default:
        logger-level: full

management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    com:
      netflix:
        discovery: OFF
    org:
      springframework:
        web: DEBUG