spring:
  application:
    name: discovery-service
  cloud:
    config:
      fail-fast: true
      username: config-client
      password: JnJc&4Y+9:+vFpmg
  config:
    import: "optional:configserver:"
